--- # copy a file from server to host
- hosts: webservwers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: copying  a file
      copy:
        src: /home/ansible/index.html
        dest: /home/ansible
        owner: pavan
