---
- name: download and install tomcat
  connection: ssh
  hosts: webservwers
  become: true
  user: ansible

  tasks:
    - name: Install java on redhat
      yum: 
       name: java
       state: installed
      when: ansible_os_family == "RedHat"

    - name: Install java on debian
      apt: 
       name: default-jdk
       state: present
      when: ansible_os_family == "Debian"


    - name: Download tomcat package
      get_url:
         url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.87/bin/apache-tomcat-8.5.87.tar.gz
         dest: /opt

    - name: Extract tomcat s/w
      unarchive:
        src: /opt/apache-tomcat-8.5.87.tar.gz
        dest: /opt
        remote_src: yes

    - name: providing executable permissions
      file:
        path: /opt/apache-tomcat-8.5.87/bin/startup.sh


    - name: start tomcat service
      shell: nohup ./startup.sh
      args: 
        chdir: /opt/apache-tomcat-8.5.87/bin











