--- # my handlers playbook

- hosts: webservwers
  user: ansible
  become: yes
  connection: ssh


  tasks:
    - name: Installing httpd in webservwers
      action: yum name=httpd state=present
      notify: start httpd service
 
  handlers:      
    - name: start httpd service
      action: service name=httpd state=started
