--- # software removal 
- name: s/w removal process
  hosts: webservwers
  user: ansible
  connection: ssh
  become: yes

  tasks:
    - name: remove package into hosts
      yum:
        name: docker
        state: absent
