--- # my vars section
- hosts: all
  user: ansible
  connection: ssh
  become: true

  vars:
    pkgname: httpd

  tasks:
    - name: installing httpd on webservwers
      action: yum name:'{{pkgname}}' state=present
